FROM node:15.14.0-alpine3.13

ARG GOOGLE_MAPS_API_KEY
ARG GOOGLE_MAPS_MAP_ID
ARG GA_MEASUREMENT_ID
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=$GOOGLE_MAPS_MAP_ID
ENV NEXT_PUBLIC_GA_MEASUREMENT_ID=$GA_MEASUREMENT_ID

WORKDIR /app
EXPOSE 3000
CMD ["yarn", "start"]

COPY yarn.lock .
COPY package.json .
RUN yarn --frozen-lockfile
COPY . .
RUN yarn build
